CREATE DATABASE QL_KHOI	 -- KHÔNG ĐƯỢC THAY ĐỔI ĐỂ KHỚP VỚI connect 
CREATE TABLE TAIKHOAN
(
	TENDANGNHAP VARCHAR(100) NOT NULL PRIMARY KEY,
	MATKHAU VARCHAR(100) NOT NULL,
	TENCHUTAIKHOAN NVARCHAR(200),
	QUYEN INT
)

CREATE TABLE LOAISANPHAM
(
	MALOAISP VARCHAR(50) PRIMARY KEY,
	TENLOAISP NVARCHAR(200) NOT NULL,
)


CREATE TABLE SANPHAM
(
	MASANPHAM VARCHAR(50) NOT NULL PRIMARY KEY,
	TENSANPHAM NVARCHAR(200),
	GIA FLOAT NOT NULL,
	THONGTIN NVARCHAR(MAX),
	MALOAISP VARCHAR(50) CONSTRAINT FK_SANPHAM_MALOAISP FOREIGN KEY REFERENCES LOAISANPHAM(MALOAISP) ON DELETE CASCADE,
)


CREATE TABLE CTHOADON
(
	MACTHOADON INT IDENTITY PRIMARY KEY,
	MAHOADON INT CONSTRAINT FK_CTHOADON_MAHOADON FOREIGN KEY REFERENCES HOADON(MAHOADON) ON DELETE CASCADE ,
	MASANPHAM VARCHAR(50) CONSTRAINT FK_CTHOADON_MASANPHAM FOREIGN KEY REFERENCES SANPHAM(MASANPHAM) ON DELETE CASCADE ,
	DONGIA FLOAT,
	SOLUONG INT NOT NULL DEFAULT 0,
)


CREATE TABLE HOADON
(
	MAHOADON INT IDENTITY PRIMARY KEY,
	TENDANGNHAP VARCHAR(100) CONSTRAINT FK_HOADON_TENDANGNHAP FOREIGN KEY REFERENCES TAIKHOAN(TENDANGNHAP) ON DELETE CASCADE ,
	MAKHACHHANG VARCHAR(50) CONSTRAINT FK_HOADON_MAKHACHHANG FOREIGN KEY REFERENCES KHACHHANG(MAKHACHHANG) ON DELETE CASCADE,
	TONGTIEN FLOAT,
	GIAMGIA FLOAT,
	PHIVANCHUYEN FLOAT,
	THANHTOAN FLOAT,
	KHACHDUA FLOAT,
	TIENTHUA FLOAT,
	THOIGIAN DATETIME
	--MATHANHTOAN INT NOT NUL FOREIGN KEY REFERENCES THANHTOAN(MATHANHTOAN)
)


CREATE TABLE KHACHHANG
(
	MAKHACHHANG VARCHAR(50) PRIMARY KEY,
	TENKHACHHANG NVARCHAR(200),
	NGAYSINH DATE,
	DIACHI NVARCHAR(100),
	SDT VARCHAR(50),
	LOAIKHACHHANG NVARCHAR(100),
	NGAYLAP DATE,
	GHICHU NVARCHAR(MAX)
)


CREATE TABLE NGUYENLIEU
(
	MANGUYENLIEU VARCHAR(50) NOT NULL PRIMARY KEY,
	TENNGUYENLIEU NVARCHAR(200) NOT NULL
)

CREATE TABLE CTNGUYENLIEU
(
	MANGUYENLIEU VARCHAR(50) CONSTRAINT FK_CTNGUYENLIEU_MANGUYENLIEU FOREIGN KEY REFERENCES NGUYENLIEU(MANGUYENLIEU) ON DELETE CASCADE,
	DONVITINH NVARCHAR(100),
	TONKHO FLOAT,
	HANSUDUNG DATE
)


CREATE TABLE NHACUNGCAP
(
	MANCC VARCHAR(50) PRIMARY KEY,
	TENNCC NVARCHAR(200),
	SDT VARCHAR(50),
	DIACHI NVARCHAR(200)
)


CREATE TABLE NHAPNGUYENLIEU
(
	MANHAPNL INT NOT NULL IDENTITY PRIMARY KEY,
	MANCC VARCHAR(50) CONSTRAINT FK_NHAPNGUYENLIEU_MANCC FOREIGN KEY REFERENCES NHACUNGCAP(MANCC) ON DELETE CASCADE,
	TENDANGNHAP VARCHAR(100) CONSTRAINT FK_NHAPNGUYENLIEU_TENDANGNHAP FOREIGN KEY REFERENCES TAIKHOAN(TENDANGNHAP) ON DELETE CASCADE,
	NGAYNHAP DATETIME,
	TONGTIEN FLOAT
)

CREATE TABLE CTNHAPNL
(
	MANHAPNL INT CONSTRAINT FK_CTNHAPNL_MANHAPNL FOREIGN KEY REFERENCES NHAPNGUYENLIEU(MANHAPNL) ON DELETE CASCADE,
	MANGUYENLIEU VARCHAR(50) CONSTRAINT FK_CTNHAPNL_MANGUYENLIEU FOREIGN KEY REFERENCES NGUYENLIEU(MANGUYENLIEU) ON DELETE CASCADE,
	SOLUONG FLOAT,
	DONVITINH NVARCHAR(50),
	HANSUDUNG DATE,
	DONGIA FLOAT
)

CREATE TABLE HUYNL
(
	MAHUYNL INT NOT NULL IDENTITY PRIMARY KEY,
	TENDANGNHAP VARCHAR(100) CONSTRAINT FK_HUYNL_TENDANGNHAP FOREIGN KEY REFERENCES TAIKHOAN(TENDANGNHAP) ON DELETE CASCADE,
	NGAYHUY DATETIME,
)

CREATE TABLE CTHUYNL
(
	MAHUYNL INT CONSTRAINT FK_CTHUYNL_MAHUYNL FOREIGN KEY REFERENCES HUYNL(MAHUYNL) ON DELETE CASCADE,
	MANGUYENLIEU VARCHAR(50) CONSTRAINT FK_CTHUYNL_MANGUYENLIEU FOREIGN KEY REFERENCES NGUYENLIEU(MANGUYENLIEU) ON DELETE CASCADE,
	DONVITINH NVARCHAR(50),
	SOLUONG FLOAT,
	HANSUDUNG DATE,
	LYDOHUY NVARCHAR(MAX)
)



CREATE TABLE CONGTHUC
(
	MASANPHAM VARCHAR(50) CONSTRAINT FK_CONGTHUC_MASANPHAM FOREIGN KEY REFERENCES SANPHAM(MASANPHAM) ON DELETE CASCADE,
	MANGUYENLIEU VARCHAR(50) CONSTRAINT FK_CONGTHUC_MANGUYENLIEU FOREIGN KEY REFERENCES NGUYENLIEU(MANGUYENLIEU) ON DELETE CASCADE,
	TIEUHAO FLOAT,
	DONVITINH NVARCHAR(100)
)


CREATE TABLE DOANHTHU
(
	MADOANHTHU INT NOT NULL IDENTITY PRIMARY KEY,
	TENDANGNHAP VARCHAR(100) CONSTRAINT FK_DOANHTHU_TENDANGNHAP FOREIGN KEY REFERENCES TAIKHOAN(TENDANGNHAP) ON DELETE CASCADE ,
	TONGTIENBAN FLOAT,
	TONGGIAMGIA FLOAT,
	TONGVANCHUYEN FLOAT,
	TONGHOADON INT,
	TONGDOANHTHU FLOAT,
	THOIGIANBD DATETIME,
	THOIGIANKT DATETIME
)

----------------------------------------------------------------




