INSERT INTO TAIKHOAN VALUES('ADMIN','1',N'Đăng Khởi',1)
INSERT INTO TAIKHOAN VALUES('ADMIN1','1',N'Đăng Khởi',0)
INSERT INTO TAIKHOAN VALUES('ADMIN2','1',N'Đăng Khởi',0)
INSERT INTO LOAISANPHAM VALUES('TS',N'Trà sữa')
INSERT INTO LOAISANPHAM VALUES('TX',N'Trà xanh')


INSERT INTO SANPHAM VALUES('TSTCDM',N'Trà sữa chân trâu đen (M)',32000,'dd','TS')
INSERT INTO SANPHAM VALUES('TSTCDL',N'Trà sữa chân trâu đen (L)',38000,'dd','TS')
INSERT INTO SANPHAM VALUES('TXNL',N'Trà xanh nho (L)',38000,'dd','TX')
INSERT INTO SANPHAM VALUES('TXNM',N'Trà xanh nho (M)',44000,'dd','TX')
INSERT INTO SANPHAM VALUES('TSKCDM',N'Trà sữa kim cương đen (M)',25000,'xd','TS')
INSERT INTO SANPHAM VALUES('TSKCDl',N'Trà sữa kim cương đen (L)',30000,'xd','TS')


INSERT INTO KHACHHANG VALUES('KH1',N'Nguyễn Văn A','2000-01-09','HHN','09123','Sơ cấp',GETDATE(),'ss')


INSERT INTO NGUYENLIEU VALUES  ('TC',N'Trân châu')
INSERT INTO NGUYENLIEU VALUES  ('SB',N'Sữa bột')

INSERT INTO CTNGUYENLIEU VALUES ('SB',N'Gói',4,'2020-02-08')
INSERT INTO CTNGUYENLIEU VALUES ('TC',N'Gói',4,'2020-02-08')
INSERT INTO CTNGUYENLIEU VALUES ('TC',N'Gói',4,'2010-03-08')
INSERT INTO CTNGUYENLIEU VALUES ('TC',N'Gói',4,'2030-01-08')


DELETE FROM NHAPNGUYENLIEU
INSERT INTO NHAPNGUYENLIEU VALUES ('TC',N'Trân châu','2020-02-02',N'Gói',5,'2020-02-08','ko')
INSERT INTO NHAPNGUYENLIEU VALUES ('TC',N'Trân châu','2020-02-02',N'Gói',4,'2010-02-08','ko')
INSERT INTO NHAPNGUYENLIEU VALUES ('TC',N'Trân châu','2020-02-02',N'Gói',5,'2030-02-08','ko')


INSERT INTO CONGTHUC VALUES ('TSTCDM','TC',0.2,N'Gói')

INSERT INTO NHACUNGCAP VALUES('CC','CAC','123','HN')
INSERT INTO NHACUNGCAP VALUES('CCA','CACA','123','HN')

                  SELECT CTHOADON.MASANPHAM , TENSANPHAM , SOLUONG, GIA , (SOLUONG * GIA) AS 'THANHTIEN' 
				  FROM SANPHAM,CTHOADON WHERE SANPHAM.MASANPHAM = CTHOADON.MASANPHAM AND MAHOADON=01  
				  GROUP BY CTHOADON.MASANPHAM, TENSANPHAM,SOLUONG,GIA ORDER BY MASANPHAM
				  2018-12-12 02:13:08.593

insert into DOANHTHU VALUES('admin','3333','22','33','11','222','2018-11-12 02:13:08.593','2018-11-12 02:13:08.594')



delete from CONGTHUC
delete from CTHOADON
delete from CTHUYNL
delete from CTNGUYENLIEU
delete from CTNHAPNL
delete from DOANHTHU
delete from HOADON
delete from HUYNL
delete from KHACHHANG
delete from LOAISANPHAM
delete from NGUYENLIEU
delete from NHACUNGCAP
delete from NHAPNGUYENLIEU
delete from SANPHAM